package day07

import (
	asrt "github.com/nasccped/godvent-of-code-2025/internal/assertion"
	"testing"
)

const input string = `.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............`

func TestPart1(t *testing.T) {
	assertion := asrt.NewAssertion(Part1(input), t)
	assertion.ExpectsEq(21).Assert()
}

func TestPart2(t *testing.T) {
	assertion := asrt.NewAssertion(Part2(input), t)
	assertion.ExpectsEq(40).Assert()
}
